name: CI con autocommit

on:
# Se ejecuta en cada push.
  push:
  # En la rama main.
    branches:
    - main
  workflow_dispatch:

# Permisos de escritura.
permissions:
  contents: write

jobs:
  generate-docs:
  # Se ejecuta en la última versión de ubuntu.
    runs-on: ubuntu-latest
    steps:
    # Clonar el repo.
      - name: Checkout repo
        uses: actions/checkout@v4

      # Configurar JDK y Maven
      - name: Setup Java JDK and Maven
        uses: actions/setup-java@v3
        with: 
          java-version: '21'
          distribution: temurin
          cache: maven

      # Genera documentación Javadoc desde cero.
      - name: Generate Javadoc
        run: mvn clean javadoc:javadoc

      # Crear la ruta de destino.
      - name: Move Javadoc to custom path
        run: |
          mkdir -p docs/_build/html
          rm -rf docs/_build/html/*
          cp -r target/site/apidocs/. docs/_build/html/

      # Subir artefactos.
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: javadoc-html
          path: docs/_build/html/

      # Configuración de Git.
      - name: Commit and push Javadoc
        run: |
          git config --global user.name "victor-gomez-tejada"
          git config --global user.email "vgomtej353@g.educaand.es"
          git add docs/_build/html/
          git commit -m "Actualización automática de Javadoc" || echo "No hay cambios para commitear"
          git push

      
